spring:
   application:
       name: cloud-config-client1   # 注册进eurkea的服务名
   cloud:
       config:
         server:
           git:
             uri: https://github.com/hrjkhan/springcloud-config.git  # github上git仓库的名称
             force-pull: true
             username: hrjkhan
             password: hanlin199687
           search-paths:
                   - springcloud-config
       lable: master
config:
  info: this is a client1  update2
